const phonicsWords = [
    ["rain", "rane", "The farmers were happy when the __________ finally came."],
    ["plane", "plaine", "We boarded the __________ for our trip to Spain."],
    ["read", "reed", "She loves to __________ mystery novels before bed."],
    ["write", "rite", "He learned how to __________ his name in school."],
    ["blue", "blew", "The sky was a clear, bright __________ today."],
    ["sea", "see", "The ship sailed across the vast __________."],
    ["meat", "meet", "For dinner, we had grilled __________ and vegetables."],
    ["dear", "deer", "She wrote a letter to her __________ friend."],
    ["flower", "flour", "A beautiful __________ bloomed in the garden."],
    ["night", "knight", "The stars twinkled in the __________ sky."],
    ["hole", "whole", "Be careful, there is a deep __________ in the ground."],
    ["pair", "pear", "She bought a new __________ of shoes."],
    ["stair", "stare", "He tripped on the last __________ while running upstairs."],
    ["to", "too", "We are going __________ the beach this weekend."],
    ["weak", "week", "After being sick, he felt very __________."],
    ["bare", "bear", "He walked on the hot sand with __________ feet."],
    ["right", "rite", "Turn __________ at the traffic light."],
    ["sun", "son", "The __________ was shining brightly in the sky."],
    ["peace", "piece", "They signed a treaty to bring __________ to the region."],
    ["board", "bored", "The teacher wrote the lesson on the white __________."],
    ["sail", "sale", "The boat raised its __________ and set off to sea."],
    ["mail", "male", "I received a letter in the __________ today."],
    ["one", "won", "She picked up __________ apple from the table."],
    ["plain", "plane", "The design was simple and __________ with no patterns."],
    ["knew", "new", "She __________ the answer before the teacher asked."],
    ["fair", "fare", "The judge made a __________ decision."],
    ["sew", "so", "She needed to __________ a button back onto her shirt."],
    ["here", "hear", "Come over __________ and sit next to me."],
    ["waist", "waste", "The belt wrapped snugly around her __________."],
    ["aisle", "isle", "The bride walked down the __________ to meet the groom."],
    ["brake", "break", "Press the __________ to stop the car."],
    ["cite", "site", "Remember to properly __________ your sources in the essay."],
    ["desert", "dessert", "Camels are well-adapted to living in the __________."],
    ["stationary", "stationery", "The bicycle remained __________ while on the stand."],
    ["capital", "capitol", "Washington, D.C. is the __________ of the United States."],
    ["kernel", "colonel", "I bit into a popcorn __________ and it got stuck in my tooth."],
    ["morning", "mourning", "The sun rises in the __________."],
    ["steal", "steel", "Thieves tried to __________ the diamond from the museum."],
    ["medal", "metal", "She won a gold __________ in the Olympics."],
    ["affect", "effect", "The new law will __________ many people."],
    ["complement", "compliment", "The red scarf was a perfect __________ to her dress."],
    ["course", "coarse", "We enrolled in a new online __________ on coding."],
    ["earn", "urn", "She worked hard to __________ a promotion."],
    ["flea", "flee", "The dog had a __________ in its fur."],
    ["horse", "hoarse", "She rode a beautiful brown __________ through the field."],
    ["moose", "mousse", "A large __________ wandered through the forest."],
    ["principal", "principle", "The school __________ made an important announcement."],
    ["sword", "soared", "The knight drew his __________ to defend the kingdom."],
    ["shear", "sheer", "The farmer had to __________ the sheep before summer."],
    ["sole", "soul", "The __________ of my shoe was worn out."],
    ["steak", "stake", "She ordered a medium-rare __________ for dinner."],
    ["taut", "taught", "The rope was pulled __________."],
    ["their", "there", "They left __________ books on the desk."],
    ["throne", "thrown", "The king sat on a golden __________."],
    ["waive", "wave", "The company decided to __________ the late fees."],
    ["witch", "which", "The wicked __________ cast a spell on the villagers."],
    ["yolk", "yoke", "The egg __________ was bright yellow."],
    ["idol", "idle", "She admired her favorite actor as her __________."],
    ["wander", "wonder", "She liked to __________ through the park on sunny days."],
    ["whither", "wither", "The flowers began to __________ without water."],
    ["wreak", "reek", "The floodwaters continued to __________ havoc on the town."],
    ["altar", "alter", "They stood at the wedding __________ to exchange vows."],
    ["bale", "bail", "The farmer stacked a __________ of hay in the barn."],
    ["bazaar", "bizarre", "We visited the open-air __________ to buy handmade crafts."],
    ["canvas", "canvass", "She painted a beautiful sunset on a __________."],
    ["cereal", "serial", "She eats a bowl of __________ every morning."],
    ["draft", "draught", "He made a rough __________ of his speech before presenting."],
    ["envelop", "envelope", "She sealed the letter in an __________."],
    ["faint", "feint", "She felt __________ after skipping lunch."],
    ["foul", "fowl", "The garbage had a __________ smell after sitting in the heat."],
    ["hail", "hale", "The storm brought heavy rain and __________."],
    ["hoard", "horde", "He had a __________ of old comic books in his attic."],
    ["jibe", "gibe", "His story didn't __________ with the witness’s account."],
    ["knead", "need", "She began to __________ the dough for the bread."],
    ["levee", "levy", "The workers built a __________ to prevent flooding."],
    ["marshal", "martial", "The general had to __________ his troops before battle."],
    ["miner", "minor", "The __________ dug deep underground for precious metals."],
    ["naval", "navel", "The country had the strongest __________ fleet in the world."],
    ["pallet", "palate", "The artist placed her paintbrushes on the wooden __________."],
    ["peal", "peel", "We heard a loud __________ of church bells in the distance."],
    ["rigger", "rigor", "The ship __________ secured the mast tightly."],
    ["sight", "site", "The Grand Canyon is a breathtaking __________ to visit."],
    ["steal", "steel", "He tried to __________ a quick glance at her paper."],
    ["troop", "troupe", "The scout __________ set up their tents in the forest."],
    ["veil", "vale", "She wore a white __________ over her face during the ceremony."],
];
